#!/usr/bin/env php
<?php

require 'bootstrap/console.php';

try { Lighty\Kernel\Console\Console::run();	}
catch (Exception $e) { echo "\n\nError : ".$e->getMessage()."\nin ".$e->getFile()." line ".$e->getLine()."\n\n"; }